name: Build Java Base Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:
  build_and_deploy_to_docker_hub:
    # The type of runner that the job will run on
    # uses https://github.com/apache/spark/blob/master/bin/docker-image-tool.sh
    # docker files are here: https://github.com/apache/spark/tree/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark
    # export ARCHS=--platform linux/arm/v7,linux/arm64/v8,linux/amd64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.2.1' # Exact version
          hadoop-version: '3.2'
      - run: spark-submit --version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create buildx context
        run: |
          docker buildx create --use
      - name: list SPARK_HOME folder
        run: |
          ls -halt $SPARK_HOME
      - name: list SPARK_HOME Python folder
        run: |
          ls -halt $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python
# This publishes to two repos:
# 1. A Plain Java Spark image to https://hub.docker.com/repository/docker/imranq2/spark/tags?page=1&ordering=last_updated
# 2. A Java Spark image with Python to https://hub.docker.com/repository/docker/imranq2/spark-py/tags?page=1&ordering=last_updated
      - name: build docker java 15 images
        run: |
          $SPARK_HOME/bin/docker-image-tool.sh -r imranq2 -t java15-${{ steps.previoustag.outputs.tag }} -X -f $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile -p $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python/Dockerfile -b java_image_tag=15-slim build
#          docker tag imranq2/spark-py:java15-${{ steps.previoustag.outputs.tag }} imranq2/spark-py:java15-latest
      - name: build docker java 17 images
        run: |
          curl https://raw.githubusercontent.com/apache/spark/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile.java17 --output $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17
          ls -halt $SPARK_HOME/kubernetes/dockerfiles/spark
          cat $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17
          $SPARK_HOME/bin/docker-image-tool.sh -r imranq2 -t java17-${{ steps.previoustag.outputs.tag }} -X -f $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17 -p $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python/Dockerfile -b java_image_tag=17-slim build
          docker tag imranq2/spark-py:java17-${{ steps.previoustag.outputs.tag }} imranq2/spark-py:java17-latest

